### ISSUE TITLE
error after instalation..

### ISSUE THREAD

**Issue by budim12** [prabowomurti/tazkiyah-pos#4]
error some code vendor bower..
```
 PHP User Error – yii\base\ErrorException
Exception 'yii\base\InvalidArgumentException' with message 'The file or directory to be published does not exist: /opt/lampp/htdocs/pos/tpos/vendor/bower/jquery/dist'

in /opt/lampp/htdocs/pos/tpos/vendor/yiisoft/yii2/web/AssetManager.php:456
```

**Comment by prabowomurti** [comment]
What `composer` version are you using? At what step the error occures?

**Comment by budim12** [comment]
My asset name is bower-asset, just rename it and solve the problem..
Thanks..

**Comment by prabowomurti** [comment]
I am not sure that's the best approach. Consider using https://asset-packagist.org/ instead of `fxp/composer-asset-plugin`

**Comment by budim12** [comment]
I just follow all the instruction, and after that i open the browser, then the error just pop up.. After i compare with my previous project, that the different..
So i just change that with works assets..
